### ISSUE TITLE
Panic on a bare `rustup target`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/multirust-rs#140]
Was wondering what the help commands were, got:

```
$ rustup target
thread '<main>' panicked at 'internal error: entered unreachable code', src/multirust-cli/rustup_mode.rs:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by alexcrichton** [comment]
(the same seems to be true for at least `rustup self` as well)

**Comment by kbknapp** [comment]
That's because `(_, _)` matches when no subcommand was used, not unrecognized subcommands which I'm assuming was the intent. 

Add the line [`.setting (AppSettings::SubcommandRequired)`](http://kbknapp.github.io/clap-rs/clap/enum.AppSettings.html#examples-1) (or [`SubcommandRequiredElseHelp`](http://kbknapp.github.io/clap-rs/clap/enum.AppSettings.html#examples-7) if youd rather the help message be displayed instead of an error message) directly after the line declaring `SubCommand::with_name ("target")`.

Same for all other subcommands which shouldn't be run bare.

**Comment by brson** [comment]
Thanks for the advice @kbknapp.
