### ISSUE TITLE
Intermittent failures on windows

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/multirust-rs#195]
I'm seeing this on the bots a lot

```
expected: 
thread 'uninstall_works_if_multirust_home_doesnt_exist' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 145, message: "The directory is not empty." } }', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
 
 
failures:
    uninstall_works_if_multirust_home_doesnt_exist
 
test result: FAILED. 34 passed; 1 failed; 3 ignored; 0 measured
 ```

**Comment by alexcrichton** [comment]
I think it's caused by [this line](https://github.com/rust-lang-nursery/multirust-rs/blob/0391ea035e34d06630eba1c9c4f47f943b39f1f1/tests/cli-self-update.rs#L198), and I guess a fix for now at least would be to use the utility function in `multirust-utils`. That function itself probably needs an overhaul though.
