### ISSUE TITLE
There's no default default toolchain

### ISSUE THREAD

**Issue by durka** [rust-lang-nursery/multirust-rs#75]
Multirust installs with no default toolchain configured, meaning every command fails. "multirust update" works, but when it tries to run `rustc -vV` for each installed toolchain, each one fails with the "no default toolchain configured" error.

Quick fix is to add "multirust default stable" to the install instructions. Better (IMO) would be to ship with stable as the default toolchain.

**Comment by Diggsey** [comment]
I don't think automatically installing stable is an acceptable option: the downloads are quite large, so if all you want is nightly, it would be quite irritating.

I will add this to the README, and possibly add a prompt to the install process to ask you what to use for the default toolchain.

`rustc -vV` should not be failing with that error even if no default toolchain is configured, since it should already be calling a specific toolchain, I'll look into that.

**Comment by brson** [comment]
Installation now configures stable by default.

**Comment by mcandre** [comment]
I'm seeing `error: no default toolchain configured` for NetBSD with the latest rustup.

**Comment by ZacRenis** [comment]
> I'm seeing `error: no default toolchain configured` for NetBSD with the latest rustup.

when i install the rust-init.exe on windows it shows "Error: no default toolchian configured.". How can i fix it?

**Comment by aurea1123** [comment]
How I can resolve this

**Comment by kinnison** [comment]
@aurea1123 there's nothing to do to resolve it.  This bug was fixed several years ago.  If you're experiencing something similar to this with modern Rustup then please open a fresh issue which explains the situation so that we can help you investigate it.
