### ISSUE TITLE
The command 'multirust doc' should open the main index 

### ISSUE THREAD

**Issue by ytain** [rust-lang-nursery/multirust-rs#83]
As I was coming back to learning the Rust language, and wanted to view the documentation that came with the stable/nightly toolchain, I was confused that I was presented with the documentation for the crate std, instead of the main index where I was looking for the language syntax to see what has changed since the last time I played with it.

My suggestion is to make 'multirust doc' command to open the main index, and the options given to this command like --std, --book, --nomicon etc., would open instead the specific pages instead of the main page.

I know that the multirust project can't help doing some trickery to inject some kind of backlink to the main index, in those pages opened by the options given to the command 'multirust doc', so changing the initial behavior is better for a beginner.

Another solution is to tell the multirust to set the doc command to open the particular page on default by using some command options that sets some internal variables that persists.

What do you think?

**Comment by crumblingstatue** [comment]
I'm the original author of multirust-doc.

My [original proposal](https://github.com/brson/multirust/issues/55#issuecomment-103044816) was mainly made fit for my own convenience, as I was accessing the libstd documentation often, and I wanted a super quick way to do that.

But since the libstd documentation is not the only piece of documentation bundled with Rust, it doesn't make sense to open it by default, instead of the index, which contains links to *all* documentation.

I agree with the proposal to open the index by default, and have various flags for quickly accessing specific docs (`--std`, `--book`, `--nomicon`).

If no one objects, I will submit a pull request implementing this behavior.

**Comment by crumblingstatue** [comment]
One thing to note: We shouldn't unnecessarily diverge in behavior from [brson/multirust](https://github.com/brson/multirust), so if this behavior gets implemented here, it should also be implemented in brson/multirust.

I'm willing to implement it in both places.

**Comment by crumblingstatue** [comment]
Okay, this should be solved by #92.

**Comment by brson** [comment]
Thanks @crumblingstatue
